Witness approval expiration
hive-engine/hivesmartcontracts pull request #14
Opened 2022-11-23 02:29 UTC by Rishi556

Expires witness approval after 5184000 blocks(approximately 180 days) of an account that hasn't made any witness approval/disapproval action. Also adds emits to successful approvals/disapprovals.

While testing this PR on the mirrornet, it was observed that witness approvals could go into the negatives when other contracts weren't properly deployed. A check has been added to ensure that unapprovals don't take them below 0.

Todo:
- [x]  Add Tests
- [x] Manual Tests

2022-11-23 16:20 UTC, primersion commented on contracts/witnesses.js
> +      witnessApproveExpireBlocks: WITNESS_APPROVE_EXPIRE_BLOCKS,
The params will also need to be updated somewhere with the new attribute, as the if statement will not be called, because the tables already exist, if i understand the code correctly.
I am not sure though where this is usually done.

2022-11-23 16:28 UTC, Rishi556 commented on contracts/witnesses.js
> +      witnessApproveExpireBlocks: WITNESS_APPROVE_EXPIRE_BLOCKS,
Resolved in https://github.com/hive-engine/hivesmartcontracts/pull/14/commits/2f7d6a697a8550a0f56ca552eb0448a0fadfe479

2022-11-23 16:28 UTC, primersion commented on contracts/witnesses.js
> +          approvalExpired: false,
Do we need the additional attribute `approvalExpired`? I think we could simply filter accounts where `approvals > 0` in `findAndExpireApprovals`.

2022-11-23 16:33 UTC, Rishi556 commented on contracts/witnesses.js
> +          approvalExpired: false,
Resolved in https://github.com/hive-engine/hivesmartcontracts/pull/14/commits/79b3268baea71f900a4ce4e0d4f015fed1af6e6c

2022-11-23 20:50 UTC, Rishi556 commented on contracts/witnesses.js
> +    } while (accounts.length === 1000);
Should be removed after deployment. Later deployments should not have this as it'll reset their last approval time.

2022-11-27 01:47 UTC, bt-cryptomancer commented on contracts/witnesses.js
> +      accounts = await api.db.find('accounts', { }, 1000, offset, []);
Instead of a blank [] for the index parameter, can you use `[{ index: '_id', descending: false }]`

That will ensure query results are always returned in the same order, avoiding potential non-deterministic behavior.  It doesn't matter much in this case since you are updating every entry in the accounts table, but in general it's good to get in the habit of using indexes:  https://github.com/hive-engine/hivesmartcontracts-wiki/blob/main/Smart-Contracts-Guide.md#avoiding-non-determinism

2022-11-27 01:50 UTC, bt-cryptomancer commented on contracts/witnesses.js
> +    params.witnessApproveExpireBlocks = WITNESS_APPROVE_EXPIRE_BLOCKS;
To ensure this whole block of code doesn't get executed more than once on subsequent deployments (in case the code block isn't removed outright after deployment), you can wrap it in a `if (!params.witnessApproveExpireBlocks) { ... }`

2022-11-27 02:21 UTC, bt-cryptomancer commented on contracts/witnesses.js
> +    const acct = await api.db.findOne('accounts', { account: from });
Instead of querying for acct again here, it would be more efficient to have this passed in as an optional function parameter (and only do the query here if it's not passed in).

2022-11-27 02:39 UTC, bt-cryptomancer commented on contracts/witnesses.js
> +  for (let i = 0; i < approvals.length; i += 1) {
You could save a bunch of queries by doing the `const acct = await api.db.findOne('accounts', { account: username });` outside this for loop and then just passing it in to removeApproval.  There are some other things you can do to optimize this process as well:  you only need to query for the account balance one time (rather than multiple times in each call of removeApproval) and updating the account object once after all the approvals are removed.  The way you're doing it now involves way more DB queries than you really need.

2022-11-27 02:43 UTC, bt-cryptomancer commented on contracts/witnesses.js
> +  await findAndExpireApprovals();
witnessApproveExpireBlocks can be passed into this function, eliminating the need to query for params again within this function.

2022-11-28 02:32 UTC, Rishi556 commented on contracts/witnesses.js
> +      accounts = await api.db.find('accounts', { }, 1000, offset, []);
Add in https://github.com/hive-engine/hivesmartcontracts/pull/14/commits/760225108775039bfaf2e6af1576cdb548ba4442#diff-26dc7edcfd60e18d37fc33e3b777bf70d456978e40dae8eca43cffcc39901f4eR63

2022-11-28 02:33 UTC, Rishi556 commented on contracts/witnesses.js
> +    params.witnessApproveExpireBlocks = WITNESS_APPROVE_EXPIRE_BLOCKS;
Added in https://github.com/hive-engine/hivesmartcontracts/pull/14/commits/760225108775039bfaf2e6af1576cdb548ba4442

2022-11-28 02:33 UTC, Rishi556 commented on contracts/witnesses.js
> +    const acct = await api.db.findOne('accounts', { account: from });
Added in https://github.com/hive-engine/hivesmartcontracts/pull/14/commits/760225108775039bfaf2e6af1576cdb548ba4442

2022-11-28 02:33 UTC, Rishi556 commented on contracts/witnesses.js
> +  await findAndExpireApprovals();
Added in https://github.com/hive-engine/hivesmartcontracts/pull/14/commits/760225108775039bfaf2e6af1576cdb548ba4442

2022-12-04 16:38 UTC, primersion commented on contracts/witnesses.js
> +  api.emit('approvalsExpired', { account: acct.account });
I would suggest using 'witnessApprovalsExpired' instead, to make it consistent with 'witnessApprovalAdded' and 'witnessApprovalRemoved'

2022-12-04 17:38 UTC, Rishi556 commented on contracts/witnesses.js
> +  api.emit('approvalsExpired', { account: acct.account });
Added in https://github.com/hive-engine/hivesmartcontracts/pull/14/commits/2d650b8ff3d7397f19c4b0c6f1ebd2362a8fa291

2022-12-18 02:18 UTC, bt-cryptomancer requested changes
Thanks for addressing earlier feedback.  I think there are still some more small improvements that can be made; please see comments below.

2022-12-18 02:18 UTC, bt-cryptomancer commented on contracts/witnesses.js
> +    await api.db.update('params', params);
These two lines of code should be moved inside the above `if (!params.witnessApproveExpireBlocks) {` block, otherwise the value of `params.witnessApproveExpireBlocks` will get overwritten with the default value whenever a contract update is deployed.

2022-12-18 02:18 UTC, bt-cryptomancer commented on contracts/witnesses.js
> +    await removeApproval(approval.from, approval.to, acct, false);
This loop can still be made more efficient.  As you did with the account query, you should lift the balance query outside of the `removeApproval` function and do it just before this for loop, then pass it into `removeApproval`.  There's no need to be repeating the same balance query for multiple calls of this function.  Also, the account update only needs to be done one time at the end.  What you really need to do is refactor this into a `removeMultipleApprovals` function.

2022-12-18 02:18 UTC, bt-cryptomancer commented on test/witnesses.js
> +      const expiringBlock = await fixture.database.getBlockInfo(53); // The block with the expiring actions
I'm having trouble understanding how this test case works.  Why do the approvals expire so fast?  I don't see any `updateParams` calls in this test case, so I would think the default value of 5184000 blocks would get used for witnessApproveExpireBlocks.

2022-12-18 02:18 UTC, bt-cryptomancer commented on test/witnesses.js
> +  it('expires votes', (done) => {
I'd like to see a stress test confirming that the smart contract remains reasonably performant when expiring several thousand votes at once.  Can you either add a new test case for that, or modify this one to cover it?

2023-01-03 06:42 UTC, Rishi556 commented on test/witnesses.js
> +      const expiringBlock = await fixture.database.getBlockInfo(53); // The block with the expiring actions
Line 42(https://github.com/hive-engine/hivesmartcontracts/pull/14/files#diff-9793bdc9ac569d36096e7b9bb8df86d8e37ffeb36e202202d252fc3e1ee62c71R42) changes the default value from 5184000 to just 50 blocks, `.replace(/WITNESS_APPROVE_EXPIRE_BLOCKS = .*;/, 'WITNESS_APPROVE_EXPIRE_BLOCKS = 50;'))` for all of testing.

2023-01-03 06:47 UTC, Rishi556 commented on contracts/witnesses.js
> +    await removeApproval(approval.from, approval.to, acct, false);
Completed in https://github.com/hive-engine/hivesmartcontracts/pull/14/commits/4282046ea177a2b9b18ce79687b0d5f9ae851c2a

2023-01-03 06:47 UTC, Rishi556 commented on contracts/witnesses.js
> +    await api.db.update('params', params);
Completed in https://github.com/hive-engine/hivesmartcontracts/pull/14/commits/4282046ea177a2b9b18ce79687b0d5f9ae851c2a

2023-01-03 07:53 UTC, Rishi556 commented on contracts/witnesses.js
> +    await removeApproval(approval.from, approval.to, acct, false);
I've reduced the db queries made within the function. The first approval query I removed entirely, and pulled the balance query outside the loop as well. I did just keep it as one function, and used the `manual` parameter to decide if to update the account within the function, or if it'll be handled outside by whatever called it.

2023-01-27 03:27 UTC, Rishi556 commented on test/witnesses.js
> +  it('expires votes', (done) => {
Added in https://github.com/hive-engine/hivesmartcontracts/pull/14/commits/05a352dfed2e7cbbec1b9678397aec16c55c9c0d The performance test is disabled by default. To enable it, change `const PERFORMANCE_CHECKS_ENABLED = false;` on line 18 in the witness test file to true.

2023-01-30 00:17 UTC, bt-cryptomancer approved these changes
Looks good, will release later this week.  Thanks for your hard work on this!

2023-01-30 00:20 UTC, merged