Add auto reward reduction to comments contract
hive-engine/hivesmartcontracts pull request #15
Opened 2023-01-25 20:44 UTC by eonwarped

Two config parameters, optional: "rewardReductionIntervalSeconds" and "rewardReductionPercentage" to control auto reduction in reward pool. Essentially when rewards are adjusted, will check against last adjustment to see if it should auto reduce the rewards pool by designated percentage.

2023-01-27 01:29 UTC, bt-cryptomancer requested changes
Mostly looks good, but you need to add more validations for the new settings (see comments below).

2023-01-27 01:29 UTC, bt-cryptomancer commented on contracts/comments.js
> +  if (!api.assert(!rewardReductionPercentage || (typeof rewardReductionPercentage === 'string' && rewardReductionPercentageDecimal.isFinite() && rewardReductionPercentageDecimal.gte('0') && rewardRed
Since these two new settings go together, you need to add code to validate that if one of them is defined & valid, then the other one also is.  Otherwise there could be problems in the calculations added to the `tokenMaintenance` function if, for example, `config.rewardReductionIntervalSeconds` is defined but `config.rewardReductionPercentage` is not.

2023-01-27 01:29 UTC, bt-cryptomancer commented on contracts/comments.js
> +  if (existingRewardPool.config.rewardReductionIntervalSeconds != rewardReductionIntervalSeconds) {
should be `!==`

2023-01-27 01:29 UTC, bt-cryptomancer commented on contracts/comments.js
> +  existingRewardPool.config.rewardReductionPercentage = rewardReductionPercentage;
If these two settings are being added to an existing pool that was created before this feature was added, then you need to validate that both settings are being added together.

Otherwise, it is fine for them to be updated individually if they were added previously.

2023-01-27 15:36 UTC, eonwarped commented on contracts/comments.js
> +  if (!api.assert(!rewardReductionPercentage || (typeof rewardReductionPercentage === 'string' && rewardReductionPercentageDecimal.isFinite() && rewardReductionPercentageDecimal.gte('0') && rewardRed
good catch! I've made sure to only apply when both settings are present, was simpler to do.

2023-01-27 15:36 UTC, eonwarped commented on contracts/comments.js
> +  existingRewardPool.config.rewardReductionPercentage = rewardReductionPercentage;
Should be resolved with the check added

2023-01-27 15:37 UTC, eonwarped commented on contracts/comments.js
> +  if (existingRewardPool.config.rewardReductionIntervalSeconds != rewardReductionIntervalSeconds) {
done

2023-01-29 01:57 UTC, bt-cryptomancer approved these changes
Looks good to me.

2023-01-29 01:57 UTC, merged