Supports witnesses using domains for their nodes rather than IPs
hive-engine/hivesmartcontracts pull request #17
Opened 2023-02-08 04:26 UTC by Rishi556

2023-02-19 01:15 UTC, bt-cryptomancer requested changes
Being able to register by both domain and IP will be a nice bit of added flexibility.  Please also add support for using domains in the `witness_action.js` utility script, and see additional comments below.

2023-02-19 01:15 UTC, bt-cryptomancer commented on test/witnesses.js
> +      transactions.push(new Transaction(37899121, fixture.getNextTxId(), 'vitalik', 'witnesses', 'register', `{ "domain": "example2.com", "RPCPort": 7000, "P2PPort": 8000, "signingKey": "STM8T4zKJuXg
In addition to testing witness registration with domains, can you also use domains in some of the other existing test cases to verify that such witnesses can be scheduled correctly?

2023-02-19 01:15 UTC, bt-cryptomancer commented on contracts/witnesses.js
> +            await api.db.update('witnesses', witness, unsets);
Can you include a test case to verify that this particular scenario (replacing a previously registered IP with a domain, or vice versa) works OK?

2023-02-19 01:15 UTC, bt-cryptomancer commented on contracts/witnesses.js
> +            domain,
Rather than always including both domain and IP here, can you add only the field that has been provided (either domain or IP)?

2023-02-19 01:40 UTC, Rishi556 commented on contracts/witnesses.js
> +            await api.db.update('witnesses', witness, unsets);
This test case should already exist, within the `registers witnesses` test case. 

We register 2 witnesses using domain and ip here: https://github.com/hive-engine/hivesmartcontracts/blob/c490161934eefd6e50bd03f5ea4df15dff4c1c53/test/witnesses.js#L114-L115

And then validate that they registered properly with those here:
https://github.com/hive-engine/hivesmartcontracts/blob/c490161934eefd6e50bd03f5ea4df15dff4c1c53/test/witnesses.js#L146
https://github.com/hive-engine/hivesmartcontracts/blob/c490161934eefd6e50bd03f5ea4df15dff4c1c53/test/witnesses.js#L156


Then flip their registration method here:
https://github.com/hive-engine/hivesmartcontracts/blob/c490161934eefd6e50bd03f5ea4df15dff4c1c53/test/witnesses.js#L167

And verify the new ones got accepted and old ones got wiped out here:
https://github.com/hive-engine/hivesmartcontracts/blob/c490161934eefd6e50bd03f5ea4df15dff4c1c53/test/witnesses.js#L198-L199
https://github.com/hive-engine/hivesmartcontracts/blob/c490161934eefd6e50bd03f5ea4df15dff4c1c53/test/witnesses.js#L208

2023-02-19 01:49 UTC, bt-cryptomancer commented on contracts/witnesses.js
> +            await api.db.update('witnesses', witness, unsets);
Ah, okay, great, I didn't notice that.  So no further action needed here.

2023-04-24 15:05 UTC, Rishi556 commented on libs/util/testing/TableAsserts.js
> +    assert.equal(logs.errors[0], message, `Error expected with message ${message}. Instead got ${logs.errors[0]}`);
Resolved https://github.com/hive-engine/hivesmartcontracts/pull/17/commits/f727a0957269ee12dadb1d74920dfc28f316f7d0#diff-1bdca75babd0d810c42d4fdd49105e701f06b4bccf1996a34ade0b9bb404b35cR10-R13

I set the default index to 0 since that's where most errors will be, but it can be overwritten.

2023-04-24 15:05 UTC, Rishi556 commented on test/witnesses.js
> +      transactions.push(new Transaction(37899121, fixture.getNextTxId(), 'vitalik', 'witnesses', 'register', `{ "domain": "example2.com", "RPCPort": 7000, "P2PPort": 8000, "signingKey": "STM8T4zKJuXg
I modified the schedule tests to test using domains: https://github.com/hive-engine/hivesmartcontracts/pull/17/commits/f727a0957269ee12dadb1d74920dfc28f316f7d0#diff-9793bdc9ac569d36096e7b9bb8df86d8e37ffeb36e202202d252fc3e1ee62c71R1215

2023-05-08 01:48 UTC, bt-cryptomancer requested changes
Thanks for addressing earlier feedback.  Mostly looks good now, just a couple minor things remaining; see comments below.

2023-05-08 01:48 UTC, bt-cryptomancer commented on witness_action.js
> +      console.log('Missing domain or IP, please add it to your .env file');
Can you also add validation that will cancel the action with an error message in the case where both IP and domain are defined in the .env?  I don't want there to be any room for ambiguity.

2023-05-08 01:48 UTC, bt-cryptomancer commented on witness_action.js
> +      console.log('Missing domain or IP, please add it to your .env file');
Same thing here, let's add a check to cancel the action with an error message in the case where both IP and domain are defined in the .env.

2023-05-17 01:29 UTC, Rishi556 commented on witness_action.js
> +      console.log('Missing domain or IP, please add it to your .env file');
Resolved in https://github.com/hive-engine/hivesmartcontracts/pull/17/commits/c0aba4520323fdf7509dd2269be1277a45d8a815

2023-05-17 01:29 UTC, Rishi556 commented on witness_action.js
> +      console.log('Missing domain or IP, please add it to your .env file');
Resolved in https://github.com/hive-engine/hivesmartcontracts/pull/17/commits/c0aba4520323fdf7509dd2269be1277a45d8a815

2023-05-24 09:00 UTC, bt-cryptomancer approved these changes
Everything looks good now.  Will merge for inclusion in the next release once you are satisfied with the testing.

2023-05-29 21:25 UTC, Rishi556 commented
We ran this over the weekend, on a testnet(and plan to leave running until tomorrow at least) and saw it all go smoothly. Invalid cases(some inadvertently) were attempted as well, and all failed. I'm pretty comfortable releasing this, if you'd like to join in the testing, feel free to. 

For release, we'll need a new tagged release first that witnesses upgrade to(due to changes in plugins/P2P), and then the contract should be deployed.

2023-07-09 02:06 UTC, merged