Add MongodDB project
hive-engine/hivesmartcontracts pull request #19
Opened 2023-03-30 04:16 UTC by Rishi556

`projection` allows for specific fields to be included or omitted in the response. Adding projection will allow for users to get just the data that they will be using, reducing bandwidth necessary. To use it, `project` can be added to the `contracts.find` and `contracts.findOne` calls within the query as an optional parameter(as well as internal calls). The default behavior is to return all fields.

2023-04-09 02:32 UTC, bt-cryptomancer requested changes
See minor comments about data validation below.

Also, if you are adding support for projections to the RPC, you might as well add it to the version of these functions exposed to the smart contracts API as well, see `libs/SmartContracts.js`.  And then you'll also need a new unit test case (or add on to an existing test case for an arbitrary contract like, say, the tokens contract) to verify the modified smart contracts API works as expected if you include a project field.

2023-04-09 02:32 UTC, bt-cryptomancer commented on libs/Database.js
> +          result = await tableData.findOne(EJSON.deserialize(query), { session: this.session, projection: project });
To be consistent, I feel like `findOne` should have the same sort of validation that is present in `find` above:

![image](https://user-images.githubusercontent.com/8011332/230750791-e5f86f3b-24c5-4314-86f0-687ba1d734c7.png)

2023-04-09 02:32 UTC, bt-cryptomancer commented on plugins/JsonRPCServer.js
> +        const { contract, table, query, project } = args;
Should treat `project` parameter consistently as with `find` function below:

![image](https://user-images.githubusercontent.com/8011332/230750907-b4e425ef-5469-43c1-ae41-82f95d6b64c7.png)

2023-05-17 00:57 UTC, Rishi556 commented on plugins/JsonRPCServer.js
> +        const { contract, table, query, project } = args;
Completed in https://github.com/hive-engine/hivesmartcontracts/pull/19/commits/e58675510b80b60dc3986c338cffc14ed40be443

2023-05-17 01:05 UTC, Rishi556 commented
How would you say is the best way to expose/test it to the SC api? Add projection to a contract and use it there is what I'm thinking, but if you have a better idea, I'll look in that direction.

2023-05-24 09:06 UTC, bt-cryptomancer commented
> How would you say is the best way to expose/test it to the SC api? Add projection to a contract and use it there is what I'm thinking, but if you have a better idea, I'll look in that direction.

This sounds like a reasonable approach.  What you could do is create a dummy test contract with one action that specifically utilizes this new feature and logs something on success.  Then have a unit test case that triggers the action and checks for the expected result in the contract logs.

2023-07-09 02:15 UTC, bt-cryptomancer commented
@Rishi556 any updates on exposing this functionality to the smart contracts API as well as RPC?  I don't consider doing that very important, though, as we don't have any immediate planned smart contract uses for it.  So if you'd like to consider this task done for now, and hold off on smart contracts API support for another time, I'm fine with that.  Please confirm either way.

2023-07-09 02:18 UTC, Rishi556 commented
I tried writing a dummy contract with a test at one point, but it ended up being a bit messy and I haven't looked at it again since then. I think we can expose it to the smart contracts if its needed at another point, especially since nothing is using it as of now.

2023-07-09 02:20 UTC, bt-cryptomancer commented
> I tried writing a dummy contract with a test at one point, but it ended up being a bit messy and I haven't looked at it again since then. I think we can expose it to the smart contracts if its needed at another point, especially since nothing is using it as of now.

Okay sounds good.  I'm happy to merge this as-is then, and consider it done for now.

2023-07-09 02:20 UTC, bt-cryptomancer approved these changes

2023-07-09 02:21 UTC, merged