Only reward wittiness who produced the round
hive-engine/hivesmartcontracts pull request #37
Opened 2023-05-18 01:48 UTC by Rishi556

Will resolve https://github.com/hive-engine/hivesmartcontracts/issues/36

2023-05-24 09:47 UTC, bt-cryptomancer reviewed
Looks good to me.  Let's run this on a testnet for a while and confirm witnesses are getting proper pay.

2023-05-24 14:39 UTC, eonwarped commented on contracts/witnesses.js
> +          // reward the current witness
Can we remove the loop and just multiply by the schedule length?

2023-05-24 14:41 UTC, eonwarped commented on contracts/witnesses.js
> +          // reward the current witness
Alternatively, what about rewarding the signers / participants? This is perhaps a little tricky because we sort of need to trust the p2p side not to exclude people on purpose. But perhaps this is something we can monitor and call out.

2023-05-24 14:44 UTC, Rishi556 commented on contracts/witnesses.js
> +          // reward the current witness
> trust the p2p side not to exclude people on purpose

That's the biggest reason that I didn't want to reward just the signers. The other option would be to require all witnesses in the round to send their signature and then reward them, but that'll make the JSON way heavier and I don't think we can even fit 20 in the 8KB that we get per custom_json.

2023-05-24 15:14 UTC, Rishi556 commented on contracts/witnesses.js
> +          // reward the current witness
What do you mean by multiplying by schedule length?

2023-05-24 16:19 UTC, eonwarped commented on contracts/witnesses.js
> +          // reward the current witness
Oh nevermind, the diff got me confused, i thought the pay was inside the loop. Looks fine.

2023-07-09 02:22 UTC, bt-cryptomancer commented
@Rishi556 can you advise on status of this item?  I believe there were some concerns raised during testing, correct?  In which case we should hold off on this for the time being.

2023-07-09 02:24 UTC, Rishi556 commented
Yup, there's some issues related to witness that were discussed which haven't been fixed yet. Best to wait for that to get fixed before merging this in.

2023-07-09 02:26 UTC, bt-cryptomancer commented
> Yup, there's some issues related to witness that were discussed which haven't been fixed yet. Best to wait for that to get fixed before merging this in.

Okay, I've changed the PR to draft status for now so that it doesn't get accidentally merged until the issues are resolved.

2023-08-05 01:04 UTC, Rishi556 commented
Small correction: The current problem will continue to happen with this, and in the long term won't lead to differing payouts, but in the short term might have some changes to lower ranking witnesses. Considering that the fix will only require a contract deployment, I still say we wait for that to be done before merging this in.

2024-02-19 03:46 UTC, bt-cryptomancer requested changes
Will approve after #55 is merged into this.

2024-02-19 03:50 UTC, Rishi556 commented
> Will approve after #55 is merged into this.

Completed

2024-02-19 04:32 UTC, bt-cryptomancer commented
Going to merge this now and begin deployment preparations.

2024-02-19 04:32 UTC, merged