Support Node 20
hive-engine/hivesmartcontracts pull request #46
Opened 2023-06-25 07:08 UTC by Rishi556

Adds support for Node.JS 20. 

The error message logged during deployment needed to be changed from using node's error message to a custom error message as node's internal changed how the message would be spit out. For now I put the deployment date as after hive block `76149072` which is approximately July 25th.

Old message: `SyntaxError: Unexpected identifier`
New message: `SyntaxError: Unexpected identifier 'CODE'`

To handle older blocks, anything with "SyntaxError: Unexpected identifier" forcibly becomes just "SyntaxError: Unexpected identifier", removing the extra stuff which stated what was the unidentified variable.

2023-07-09 02:45 UTC, bt-cryptomancer commented
@Rishi556 I've converted this to draft status as I'm not comfortable making such a fundamental change for the time being. We can revisit this in September when I'm back from summer travels.

2023-08-05 01:01 UTC, Rishi556 commented
I do think we should try and update as new releases are made, especially since Node now has a team dedicated to performance. Doing updates in smaller batches and keeping up will make it a lot easier than trying to fix support for a few node versions at once which might have many breaking changes, vs doing 1 at a time might lead to just a few. BTW this will need to be changed before deployment to change the block num.

2024-02-09 00:21 UTC, Rishi556 commented
@bt-cryptomancer Can you take a look at this. We'll have to change block number but I'd like to get this one merged in before Node 22 gets released in about 2 months

2024-02-12 21:06 UTC, eonwarped requested changes
Small comment, looks fine to me.

2024-02-12 21:06 UTC, eonwarped commented on libs/SmartContracts.js
> +      // log.error('ERROR DURING CONTRACT DEPLOYMENT: ', e);
let's re-enable this log

2024-02-12 21:06 UTC, eonwarped commented on libs/SmartContracts.js
> +      if (refHiveBlockNumber <= 76149072) { // Approximately Sunday July 25 UTC
just tracking needed change to block number

2024-02-12 22:28 UTC, Rishi556 commented on libs/SmartContracts.js
> +      if (refHiveBlockNumber <= 76149072) { // Approximately Sunday July 25 UTC
Maintainers should have the ability to make this change themselves once they are ready to merge this in.

2024-02-12 22:29 UTC, Rishi556 commented on libs/SmartContracts.js
> +      // log.error('ERROR DURING CONTRACT DEPLOYMENT: ', e);
Resolved in https://github.com/hive-engine/hivesmartcontracts/pull/46/commits/77e64027166eddf5c4424684c44c6b4e66768064

2024-02-12 22:30 UTC, Rishi556 commented
Node 16 is EOL as well, thoughts on dropping it from the test matrix?

2024-02-13 15:05 UTC, eonwarped commented on libs/SmartContracts.js
> +      if (refHiveBlockNumber <= 76149072) { // Approximately Sunday July 25 UTC
Good point, will make sure to figure out when the next window we would like to make the next change is.

2024-02-13 15:06 UTC, eonwarped commented
> Node 16 is EOL(and is approaching 6 months of EOL) as well, thoughts on dropping it from the test matrix?

deferring to @bt-cryptomancer

2024-02-19 03:54 UTC, bt-cryptomancer commented
@Rishi556 I'm fine to have Node 16 removed from the test matrix.  If we're going to do that, let's also update the minimum node version in the package.json to 18+

I will update the trigger block number after merging this to QA and after other consensus breaking changes are merged in.

2024-02-19 04:15 UTC, bt-cryptomancer commented
Looks good now, but conflict needs to be resolved before merging.

2024-02-19 04:30 UTC, merged