Allow for using block_api.get_block API
hive-engine/hivesmartcontracts pull request #61
Opened 2024-02-12 20:56 UTC by eonwarped

Prepares for eventual deprecation of condenser_api.get_block.

- Handle new output format (inner block parameter)
- Handles HIVE/HBD nai assets used in transfer op and commentOptions op
- Reformatting beneficiaries in commentOptions to match old API

Also
- Minor fixes to debuggability (hash verification mode)

2024-02-14 15:37 UTC, eonwarped commented on plugins/Blockchain.js
> +    const mainBlock = !enableHashVerification ? null : (await getBlock(newBlock.blockNumber));
Aw fine, I was thinking it should more be a secret config. But I suppose as long as everyone is responsible it should be fine.

2024-02-14 15:39 UTC, eonwarped commented on plugins/Blockchain.js
> +var gbid = 1;
Done

2024-02-14 15:39 UTC, eonwarped commented on plugins/Blockchain.js
> +      url: 'https://api.hive-engine.com/rpc/blockchain',
Done

2024-02-19 04:11 UTC, bt-cryptomancer requested changes
It looks like you've changed the enableHashVerification setting to hashVerificationNode, but forgot to make the corresponding update to config.example.json.

Also, can you please document on the PR what each of the new streamerConfig settings is for, and confirm that the default values you've selected are good values for production use (so node operators can simply copy the example when upgrading)?

2024-02-19 04:50 UTC, eonwarped commented
> It looks like you've changed the enableHashVerification setting to hashVerificationNode, but forgot to make the corresponding update to config.example.json.
> 
> Also, can you please document on the PR what each of the new streamerConfig settings is for, and confirm that the default values you've selected are good values for production use (so node operators can simply copy the example when upgrading)?

Done with config. Updating PR.

2024-02-19 05:01 UTC, bt-cryptomancer approved these changes
Thanks, looks good now.

2024-02-19 05:02 UTC, merged